src/HappyMeet/Controllers/BancoController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HappyMeet.Domain.Entities;
using HappyMeet.Domain.Requests;
using HappyMeet.Domain.Util;
using HappyMeet.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using X.PagedList;
using HappyMeet.Domain.Extensions;

namespace HappyMeet.Controllers
{
    [Authorize(Policy = ClaimConstants.BANCO_LEITURA)]
    public class BancoController : BaseController
    {
        public BancoController(IMediator mediator) : base(mediator)
        {

        }

        public async Task<IActionResult> Index(int searchCodBanco, string searchNome, string sortProperty, string sortOrder, int pagina)
        {
            var searchExpression = GetSearchExpression(searchCodBanco, searchNome);
            var response = await Mediator.Send(new FindBancosRequest(searchExpression, sortProperty, sortOrder, pagina, RegistrosPorPagina));

            var model = new BancoPresentationViewModel();

            model.Bancos = response.Value.ToArray();
            model.RegistrosPorPagina = RegistrosPorPagina;
            model.CurrentPage = pagina;
            model.TotalCount = await Mediator.Send(new FindBancoCountRequest(searchExpression));
            model.BancosPaged = new StaticPagedList<Banco>(model.Bancos, pagina, RegistrosPorPagina, model.TotalCount);

            return View(model);
        }

        public async Task<IActionResult> CreateEdit(int? id)
        {
            BancoViewModel model;
            if (id.HasValue)
            {
                var response = await Mediator.Send(new FindBancosRequest(x => x.Id.Equals(id.Value)));
                model = Mapper.Map<Banco, BancoViewModel>(response.Value.FirstOrDefault());
            }
            else
            {
                model = new BancoViewModel
                {
                    Ativo = true
                };
            }

            return View(model);
        }

        [Authorize(Policy = ClaimConstants.BANCO_ESCRITA)]
        [HttpPost]
        public async Task<IActionResult> CreateEdit(BancoViewModel model, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                Banco banco;

                string nomeArquivo;
                byte[] arquivo = FileToByteArray(file, out nomeArquivo);

                if (model.Id == 0)
                {
                    banco = Mapper.Map<BancoViewModel, Banco>(model);
                }
                else
                {
                    var find = await Mediator.Send(new FindBancosRequest(x => x.Id.Equals(model.Id)));
                    banco = find.Value.FirstOrDefault();

                    if (banco.Arquivo != null && !arquivo.Any())
                    {
                        arquivo = (byte[])banco.Arquivo.Clone();
                    }

                    Mapper.Map(model, banco);
                }

                if(!String.IsNullOrEmpty(nomeArquivo)) banco.NomeArquivo = nomeArquivo;

                banco.Arquivo = arquivo;

                var response = await Mediator.Send(new PersistBancoRequest(banco));

                if (response)
                {
                    Success(response.Value);
                    return RedirectToAction("Index");
                }
                AddError(response.Error);
            }

            return View(model);
        }


        public async Task<ActionResult> DownloadArquivo(int id)
        {
            var response = await Mediator.Send(new FindBancosRequest(x => x.Id.Equals(id)));

            var banco = response.Value.FirstOrDefault();

            if (banco.Arquivo == null || banco.Arquivo.Length == 0)
            {
                return Json(new { success = false });
            }

            //MemoryStream fileStream = new MemoryStream(banco.Arquivo);
            return new FileContentResult(banco.Arquivo, "application/octet-stream")
            {
                FileDownloadName = banco.NomeArquivo
            };
        }

        private Expression<Func<Banco, bool>> GetSearchExpression(int searchCodBanco, string searchNome)
        {
            Expression<Func<Banco, bool>> exp = x => true;

            if (searchCodBanco > 0)
            {
                exp = exp.And(x => x.Codigo.Equals(searchCodBanco));
            }

            if (!String.IsNullOrEmpty(searchNome))
            {
                exp = exp.And(x => x.NomeBanco.ToLower().Contains(searchNome.ToLower()));
            }

            return exp;
        }
    }
}

src/HappyMeet/Views/Shared/_Blank.cshtml
@inject AppConfig Config
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico">
    <title>@ViewData["Title"]  – @Config.NomeCliente – B3 Boletos</title>
    @{await Html.RenderPartialAsync("_CssVarsPartial");}
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/selectize/dist/css/selectize.css" />
        <link rel="stylesheet" href="~/css/views/_helpers.css" />
        <link rel="stylesheet" href="~/css/views/cliente.css" />
        <link rel="stylesheet" href="~/css/views/template.css" />
        <link rel="stylesheet" href="~/css/views/boletos.css" />
        <link rel="stylesheet" href="~/css/views/banco.css" />
        <link rel="stylesheet" href="~/css/views/login.css" />
        <link rel="stylesheet" href="~/css/views/configuracao.css" />
        <link rel="stylesheet" href="~/css/views/accessdenied.css" />
        <link rel="stylesheet" href="~/css/views/resetpassword.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @{
        var alerts = TempData.ContainsKey(Alert.TempDataKey)
                    ? TempData.Get<List<Alert>>(Alert.TempDataKey)
                    : new List<Alert>();
        foreach (var alert in alerts)
        {
            var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
            <div class="alert alert-@alert.AlertStyle alert-dismissible fade show" role="alert">
                @Html.Raw(alert.Message)
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
    }
    @RenderBody()
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/popper.min.js"></script>
        <script src="~/lib/fontawesome/fontawesome-all.min.js"></script>
        <script src="~/lib/selectize/dist/js/standalone/selectize.js"></script>
        <script src="~/lib/jquery-mask/dist/jquery.mask.js"></script>
        <script src="~/lib/jquery-cookie/jquery.cookie.js"></script>
        <script src="~/lib/flatpickr/flatpickr.min.js"></script>
        <script src="~/lib/sweetalert/sweetalert2.all.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/js/plugins.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T">
        </script>
        <script src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"
                integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe"
                asp-fallback-src="~/lib/fontawesome/fontawesome-all.min.js"
                asp-fallback-test="window.FontAwesome"
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    <script type="text/template" id="loadingTemplate">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </script>
</body>
</html>

src/HappyMeet/Views/Shared/_CssVarsPartial.cshtml
@inject AppConfig Config
<style>
    :root {
        --corPrimaria: @Config.CorPrimaria;
        --corSecundaria: @Config.CorSecundaria;
        --corFonte: @Config.CorFonte;
    }
</style>

src/HappyMeet/Views/Shared/_Layout.cshtml
@using HappyMeet.Domain.Util
@inject AppConfig Config
@using System.Reflection;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico">
    <title>@ViewData["Title"] – @Config.NomeCliente – B3 Boletos</title>
    @{await Html.RenderPartialAsync("_CssVarsPartial");}

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/selectize/dist/css/selectize.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-year-calendar/css/bootstrap-year-calendar.css" />
        <link rel="stylesheet" href="~/lib/flatpickr/flatpickr.min.css" />
        <link rel="stylesheet" href="~/lib/trumbowyg/dist/ui/trumbowyg.css" />
        <link rel="stylesheet" href="~/css/views/_helpers.css" />
        <link rel="stylesheet" href="~/css/views/_animations.css" />
        <link rel="stylesheet" href="~/css/views/cliente.css" />
        <link rel="stylesheet" href="~/css/views/template.css" />
        <link rel="stylesheet" href="~/css/views/boletos.css" />
        <link rel="stylesheet" href="~/css/views/banco.css" />
        <link rel="stylesheet" href="~/css/views/login.css" />
        <link rel="stylesheet" href="~/css/views/accessdenied.css" />
        <link rel="stylesheet" href="~/css/views/feriado.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div class="body-container">

        <nav id="main-navigation" class="main-navigation">

            <a class="nav-logo" href="https://b3boletos.com.br" target="_blank" title="Voltar para a página inicial">B3 Consultoria</a>

            <ul class="nav-menu">
                @if (User.HasPermission(ClaimConstants.USUARIO_LEITURA))
                {
                    <li>
                        <a title="Usuários" asp-controller="Usuario" asp-action="Index">
                            <i class="fas fa-user"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.CLIENTE_LEITURA))
                {
                    <li>
                        <a title="Clientes" asp-controller="Cliente" asp-action="Index">
                            <i class="fas fa-user-tag"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.REPRESENTANTE_LEITURA))
                {
                    <li>
                        <a title="Representantes" asp-controller="Representante" asp-action="Index">
                            <i class="far fa-address-card"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.BOLETO_LEITURA))
                {
                    <li>
                        <a title="Boletos" asp-controller="Boletos" asp-action="Index">
                            <i class="fas fa-barcode"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.TEMPLATE_LEITURA))
                {
                    <li>
                        <a title="Templates" asp-controller="Template" asp-action="Index">
                            <i class="far fa-envelope"></i>
                        </a>
                    </li>
                }


                @if (User.HasPermission(ClaimConstants.PADRAO_ENVIO_EMAIL_LEITURA))
                {
                    <li>
                        <a title="Padrões de Envio de Email" asp-controller="PadraoEnvioEmail" asp-action="Index">
                            <i class="fab fa-telegram-plane"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.BANCO_LEITURA))
                {
                    <li>
                        <a title="Bancos" asp-controller="Banco" asp-action="Index">
                            <i class="fas fa-piggy-bank"></i>
                        </a>
                    </li>
                }

                @if (User.HasPermission(ClaimConstants.LOG_EMAIL_LEITURA))
                {
                    <li>
                        <a title="Log de Envio de Email" asp-controller="LogEnvioEmail" asp-action="Index">
                            <i class="far fa-file-alt"></i>
                        </a>
                    </li>
                }



                @if (User.HasPermission(ClaimConstants.FERIADO_LEITURA))
                {
                    <li>
                        <a title="Feriados" asp-controller="Feriado" asp-action="Index">
                            <i class="far fa-calendar-alt"></i>
                        </a>
                    </li>
                }
            </ul>
        </nav>

        <div class="container-fluid body-content">
            <div class="row row-header">
                <div class="col-12">
                    <div class="container-row-header">

                        <div class="logo-client">
                            @{var logo = !String.IsNullOrEmpty(Config.ImagemLogoBase64) ? Config.ImagemLogoBase64 : "~/images/default/logo-default.png"; }
                            <a asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="@logo" alt="B3 Boletos – @Config.NomeCliente">
                            </a>
                        </div>
                        <aside class="acessos">
                            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="far fa-user"></i> @(User.FindFirst("Nome").Value)
                            </button>
                            <a href="#" id="open-modal-contato">
                                <i class="fas fa-phone-square"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="#">Alterar minha senha</a>

                                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                                    <button type="submit" class="dropdown-item">Sair</button>
                                </form>

                                <h6 class="dropdown-header">
                                    <small>
                                        Versão @Assembly.GetEntryAssembly().GetVersion()
                                    </small>
                                </h6>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    @{
                        var alerts = TempData.ContainsKey(Alert.TempDataKey)
                                    ? TempData.Get<List<Alert>>(Alert.TempDataKey)
                                    : new List<Alert>();
                        foreach (var alert in alerts)
                        {
                            var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
                            <div class="alert alert-@alert.AlertStyle alert-dismissible fade show" role="alert">
                                @Html.Raw(alert.Message)
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                    }
                </div>
            </div>

            @RenderBody()
        </div>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/popper.min.js"></script>
        <script src="~/lib/fontawesome/fontawesome-all.min.js"></script>
        <script src="~/lib/selectize/dist/js/standalone/selectize.js"></script>
        <script src="~/lib/bootstrap-year-calendar/js/bootstrap-year-calendar.js"></script>
        <script src="~/lib/jquery-mask/dist/jquery.mask.js"></script>
        <script src="~/lib/jquery-cookie/jquery.cookie.js"></script>
        <script src="~/lib/stringmask/stringmask.js"></script>
        <script src="~/lib/flatpickr/flatpickr.min.js"></script>
        <script src="~/lib/sweetalert/sweetalert2.all.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/js/plugins.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T">
        </script>
        <script src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"
                integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe"
                asp-fallback-src="~/lib/fontawesome/fontawesome-all.min.js"
                asp-fallback-test="window.FontAwesome"
                crossorigin="anonymous">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)

    <script type="text/template" id="loadingTemplate">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </script>

    <div class="modal fade" id="contato" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document" style="height: 436px;">
            <div class="modal-content">
                <div class="modal-header primary-bg c-white">
                    <h5 class="modal-title">Dúvidas?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body p-t-20">
                    <h4>Telefone:</h4>
                    <p>@Config.TelefoneContato</p>
                    @if (!String.IsNullOrEmpty(Config.RamalContato))
                    {
                        @Html.Raw($"Ramal: {Config.RamalContato}");
                    }
                    <hr>
                    <h4>Email:</h4>
                    <a href="mailto:@Config.EmailContato">@Config.EmailContato</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

src/HappyMeet/Views/Shared/_OrderTemplatePartial.cshtml
<script type="text/template" id="templateOrder">
    <input class="js-order js-order-down hidden" type="radio" name="sortOrder" value="OrderByDescending" {{descendingChecked}}>
    <input class="js-order js-order-up hidden" type="radio" name="sortOrder" value="OrderBy" {{ascendingChecked}}>
    <div class="arrows">
        <div class="js-none"><i class="fas fa-arrows-alt-v"></i></div>
        <div class="js-up"><i class="fas fa-arrow-up"></i></div>
        <div class="js-down"><i class="fas fa-arrow-down"></i></div>
    </div>
</script>